apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: granite-copilot
    component: orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: granite-copilot
      component: orchestrator
  template:
    metadata:
      labels:
        app: granite-copilot
        component: orchestrator
    spec:
      serviceAccountName: orchestrator-sa
      containers:
        - name: orchestrator
          image: your-registry/granite-copilot-orchestrator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://nats:4222"
            - name: NEO4J_URI
              value: "bolt://neo4j:7687"
            - name: NEO4J_USER
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: neo4j-credentials
                  key: password
            - name: WATSONX_APIKEY
              valueFrom:
                secretKeyRef:
                  name: watsonx-credentials
                  key: apiKey
            - name: WATSONX_URL
              valueFrom:
                secretKeyRef:
                  name: watsonx-credentials
                  key: url
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: orchestrator-config
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
